import {
  LayoutDashboard,
  Mail,
  Users,
  ShieldCheck,
  Network,
  GitBranch,
  FileSearch,
  FileBarChart2,
  Building2,
  CalendarDays,
  Coins,
  Gauge,
  Landmark,
  Workflow,
  ClipboardCheck,
  CalendarRange,
  FileSpreadsheet,
  KeyRound,
  ShieldQuestion,
  BookOpen,
  Briefcase,
  List,
  HelpCircle,
  TrendingUp,
  FileText,
  Calendar,
  ArrowLeftRight,
  Plus,
  History,
  SearchCheck,
  Wallet,
  PiggyBank,
  CircleUser,
  Contact,
  ListTree,
  Layers,
  LayoutGrid,
  Link2,
  Wrench,
  Scale,
  ShieldAlert,
  SearchCode,
  AlertTriangle,
  RefreshCw,
  ScrollText,
  ListOrdered,
  UserPlus,
  Search,
  IdCard,
  ClipboardList,
  Package,
  CreditCard,
  type LucideIcon,
} from "lucide-react";
import { Permissions } from "@/lib/rbac/permissions";

export interface NavItem {
  /** Shown in the sidebar; keep short when possible. */
  label: string;
  /** Optional longer description for `title` tooltip. */
  title?: string;
  href: string;
  icon?: LucideIcon;
  permissions?: ReadonlyArray<string>;
  permissionMode?: "all" | "any";
}

export interface NavSection {
  id: string;
  /** Shown in the sidebar; keep short (roughly ≤22 chars) so the narrow rail stays clean. */
  label: string;
  /** Optional longer name for tooltips when label is abbreviated. */
  title?: string;
  icon?: LucideIcon;
  items: NavItem[];
  permissions?: ReadonlyArray<string>;
}

export const navSections: NavSection[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    items: [
      { label: "Overview", href: "/dashboard", icon: LayoutDashboard },
      {
        label: "Inbox",
        title: "Staff notifications (personal and shared queues such as compliance).",
        href: "/inbox",
        icon: Mail,
      },
    ],
  },
  {
    id: "identity",
    label: "Identity & Access",
    title: "User lifecycle, roles, delegations, workflows, audit, compliance",
    icon: Users,
    permissions: [
      Permissions.AdminUsersRead,
      Permissions.AdminRolesRead,
      Permissions.AdminDoaRead,
      Permissions.AuditRead,
      Permissions.ReportGenerate,
    ],
    items: [
      {
        label: "Overview",
        title: "Shortcuts for users, roles, access policy, and audits.",
        href: "/identity",
        icon: Users,
        permissions: [
          Permissions.AdminUsersRead,
          Permissions.AdminRolesRead,
          Permissions.AdminDoaRead,
          Permissions.AuditRead,
          Permissions.ReportGenerate,
        ],
        permissionMode: "any",
      },
      {
        label: "Users",
        title: "Create, search, and maintain operator identities.",
        href: "/identity/users",
        icon: Users,
        permissions: [Permissions.AdminUsersRead],
      },
      {
        label: "Roles",
        title: "Role definitions, inheritance, and membership.",
        href: "/identity/roles",
        icon: ShieldCheck,
        permissions: [Permissions.AdminRolesRead],
      },
      {
        label: "Permission catalogue",
        title: "Browse effective permission codes used in policies.",
        href: "/identity/permissions",
        icon: ListTree,
        permissions: [Permissions.AdminRolesRead],
      },
      {
        label: "Delegations",
        title: "Delegate signing and approval authority between operators.",
        href: "/identity/delegations",
        icon: Network,
        permissions: [Permissions.AdminDoaRead],
      },
      {
        label: "Approval workflows",
        title: "Configure how sensitive identity changes are approved.",
        href: "/identity/approval-workflows",
        icon: GitBranch,
        permissions: [Permissions.AdminDoaRead],
      },
      {
        label: "Security audit",
        title: "Review authentication and authorization events.",
        href: "/security/audit",
        icon: FileSearch,
        permissions: [Permissions.AuditRead],
      },
      {
        label: "Compliance reports",
        title: "Generate identity and access compliance artefacts.",
        href: "/security/compliance",
        icon: FileBarChart2,
        permissions: [Permissions.ReportGenerate],
      },
    ],
  },
  {
    id: "general-ledger",
    label: "General Ledger",
    icon: BookOpen,
    permissions: [Permissions.GlRead, Permissions.GlApprove],
    items: [
      {
        label: "Overview",
        href: "/general-ledger",
        icon: BookOpen,
        permissions: [Permissions.GlRead, Permissions.GlApprove],
        permissionMode: "any",
      },
      {
        label: "Chart of accounts",
        title: "Maintain the account tree, currency, and normal balance.",
        href: "/general-ledger/chart-of-accounts",
        icon: Layers,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Operational mappings",
        title: "Map operational account types to ledger accounts.",
        href: "/general-ledger/operational-accounts",
        icon: Link2,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Fiscal periods",
        href: "/general-ledger/fiscal-periods",
        icon: CalendarRange,
        permissions: [Permissions.GlRead],
      },
      {
        label: "GL approvals queue",
        href: "/operations/gl-approvals",
        icon: ClipboardCheck,
        permissions: [Permissions.GlApprove],
      },
      {
        label: "Trial balance",
        title: "Point-in-time balances before period close.",
        href: "/general-ledger/trial-balance",
        icon: Scale,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Transaction lookup",
        title: "Find GL transactions by id or business reference.",
        href: "/general-ledger/transaction-lookup",
        icon: SearchCode,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Journal by account",
        title: "Posted lines and running detail for one GL account.",
        href: "/general-ledger/journal-by-account",
        icon: ListOrdered,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Suspense",
        title: "Work items parked in suspense until reconciled.",
        href: "/general-ledger/suspense",
        icon: AlertTriangle,
        permissions: [Permissions.GlRead],
      },
      {
        label: "AML review queue",
        title: "Postings held for sanctions and AML review.",
        href: "/compliance/aml-review",
        icon: ShieldAlert,
        permissions: [Permissions.GlRead],
      },
      {
        label: "FX revaluation",
        title: "Revalue foreign balances at new rates.",
        href: "/general-ledger/revaluation",
        icon: RefreshCw,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Audit explorer",
        title: "Immutable trail of GL configuration and posting changes.",
        href: "/general-ledger/audit",
        icon: ScrollText,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Financial statements",
        href: "/general-ledger/reports",
        icon: FileSpreadsheet,
        permissions: [Permissions.GlRead],
      },
    ],
  },
  {
    id: "customers",
    label: "Customers",
    title: "Customer master data and servicing",
    icon: Contact,
    permissions: [Permissions.CustomerRead, Permissions.CustomerWrite],
    items: [
      {
        label: "Overview",
        title: "Shortcuts across customer servicing areas.",
        href: "/customers",
        icon: Contact,
        permissions: [Permissions.CustomerRead, Permissions.CustomerWrite],
        permissionMode: "any",
      },
      {
        label: "Directory",
        title: "Paged search across the customer master file.",
        href: "/customers/directory",
        icon: List,
        permissions: [Permissions.CustomerRead],
      },
      {
        label: "New customer",
        title: "Onboard a new customer record.",
        href: "/customers/new",
        icon: UserPlus,
        permissions: [Permissions.CustomerWrite],
      },
      {
        label: "KYC workspace",
        title: "KYC status, tasks, and evidence by customer.",
        href: "/customers/kyc-hub",
        icon: ClipboardList,
        permissions: [Permissions.CustomerRead],
      },
      {
        label: "ID documents",
        title: "Identity documents and verification artefacts.",
        href: "/customers/document-hub",
        icon: IdCard,
        permissions: [Permissions.CustomerPiiRead],
      },
    ],
  },
  {
    id: "accounts",
    label: "Accounts",
    title: "Customer accounts and deposits",
    icon: Wallet,
    permissions: [Permissions.AccountRead, Permissions.AccountWrite],
    items: [
      {
        label: "Overview",
        href: "/accounts",
        icon: Wallet,
        permissions: [Permissions.AccountRead, Permissions.AccountWrite],
        permissionMode: "any",
      },
      {
        label: "Directory",
        title: "Search and filter accounts across the portfolio.",
        href: "/accounts/directory",
        icon: List,
        permissions: [Permissions.AccountRead],
      },
      {
        label: "New account",
        title: "Open a new account for an onboarded customer.",
        href: "/accounts/new",
        icon: UserPlus,
        permissions: [Permissions.AccountWrite],
      },
      {
        label: "Lookup",
        title: "Resolve an account by id, number, or IBAN.",
        href: "/accounts/lookup",
        icon: Search,
        permissions: [Permissions.AccountRead],
      },
      {
        label: "Portfolio reports",
        title: "Slice the book by product type or operational status.",
        href: "/accounts/reports",
        icon: FileSpreadsheet,
        permissions: [Permissions.AccountRead],
      },
      {
        label: "Operations",
        title: "Batch status/close, dormancy, expired holds, interest accrual",
        href: "/accounts/operations",
        icon: Wrench,
        permissions: [Permissions.AccountWrite],
      },
    ],
  },
  {
    id: "transaction-processing",
    label: "Transaction Processing",
    title: "Payments, fees, limits, compensation, and account history",
    icon: ArrowLeftRight,
    permissions: [
      Permissions.TransactionRead,
      Permissions.TransactionWrite,
      Permissions.FeeRead,
      Permissions.VelocityLimitRead,
      Permissions.CompensationRead,
      Permissions.AccountRead,
      Permissions.PaymentInitiate,
      Permissions.AdminConfigWrite,
    ],
    items: [
      {
        label: "Overview",
        href: "/transaction-processing",
        icon: Briefcase,
        permissions: [
          Permissions.TransactionRead,
          Permissions.FeeRead,
          Permissions.VelocityLimitRead,
          Permissions.CompensationRead,
          Permissions.AccountRead,
        ],
        permissionMode: "any",
      },
      {
        label: "Transactions",
        title: "Search, initiate, and repair payment rail activity.",
        href: "/transaction-processing/transactions",
        icon: List,
        permissions: [Permissions.TransactionRead],
      },
      {
        label: "Fee rules",
        href: "/transaction-processing/fees/rules",
        icon: Coins,
        permissions: [Permissions.FeeRead],
      },
      {
        label: "Fee waivers",
        href: "/transaction-processing/fees/waivers",
        icon: PiggyBank,
        permissions: [Permissions.FeeRead],
      },
      {
        label: "Velocity limits",
        href: "/transaction-processing/velocity-limits",
        icon: Gauge,
        permissions: [Permissions.VelocityLimitRead],
      },
      {
        label: "Compensation workflows",
        href: "/transaction-processing/compensation/workflows",
        icon: Workflow,
        permissions: [Permissions.CompensationRead],
      },
      {
        label: "Account transactions",
        title: "Account statement layer and linked vouchers.",
        href: "/transaction-processing/account-transactions",
        icon: Wallet,
        permissions: [Permissions.AccountRead],
      },
    ],
  },
  {
    id: "exchange-rates",
    label: "Exchange Rates",
    icon: Landmark,
    permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
    items: [
      {
        label: "Overview",
        title: "Lookup, convert, and maintain institutional FX rates.",
        href: "/exchange-rates",
        icon: Landmark,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Today's rates",
        title: "Managed pairs, edit mids, and trigger ECB sync.",
        href: "/exchange-rates/today",
        icon: LayoutGrid,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Currencies",
        href: "/exchange-rates/currencies",
        icon: List,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Currency support",
        href: "/exchange-rates/currency-support",
        icon: HelpCircle,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Latest rate",
        href: "/exchange-rates/latest-rate",
        icon: TrendingUp,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Rate details",
        href: "/exchange-rates/rate-details",
        icon: FileText,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Rate by date",
        href: "/exchange-rates/rate-by-date",
        icon: Calendar,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Convert",
        href: "/exchange-rates/convert",
        icon: ArrowLeftRight,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Create rate",
        href: "/exchange-rates/create-rate",
        icon: Plus,
        permissions: [Permissions.ExchangeRateWrite],
      },
      {
        label: "Rate history",
        href: "/exchange-rates/rate-history",
        icon: History,
        permissions: [Permissions.ExchangeRateWrite],
      },
      {
        label: "Rate exists",
        href: "/exchange-rates/rate-exists",
        icon: SearchCheck,
        permissions: [Permissions.ExchangeRateWrite],
      },
    ],
  },
  {
    id: "loans",
    label: "Loans",
    title: "Lending products, pipelines, and loan servicing",
    icon: PiggyBank,
    permissions: [
      Permissions.LoanRead,
      Permissions.LoanWrite,
      Permissions.LoanApprove,
      Permissions.LoanDisburse,
      Permissions.LoanDisburseApprove,
      Permissions.LoanWriteOff,
      Permissions.LoanRestructure,
      Permissions.LoanRestructureApprove,
      Permissions.LoanCollect,
      Permissions.LoanCollectApprove,
    ],
    items: [
      {
        label: "Overview",
        href: "/loans",
        icon: PiggyBank,
        permissions: [
          Permissions.LoanRead,
          Permissions.LoanWrite,
          Permissions.LoanApprove,
          Permissions.LoanDisburse,
          Permissions.LoanDisburseApprove,
          Permissions.LoanWriteOff,
          Permissions.LoanRestructure,
          Permissions.LoanRestructureApprove,
          Permissions.LoanCollect,
          Permissions.LoanCollectApprove,
        ],
        permissionMode: "any",
      },
      {
        label: "Products",
        title: "Loan product templates, rates, and eligibility rules.",
        href: "/loans/products",
        icon: Package,
        permissions: [Permissions.LoanRead],
      },
      {
        label: "Applications",
        title: "Origination queues from intake to booking.",
        href: "/loans/applications",
        icon: ClipboardList,
        permissions: [Permissions.LoanRead],
      },
      {
        label: "New application",
        title: "Start underwriting for a new facility.",
        href: "/loans/applications/new",
        icon: UserPlus,
        permissions: [Permissions.LoanWrite],
      },
      {
        label: "Accounts",
        title: "Booked loans: balances, schedules, and covenants.",
        href: "/loans/accounts",
        icon: Wallet,
        permissions: [Permissions.LoanRead],
      },
      {
        label: "Payments",
        title: "Collections, allocations, and reversals across facilities.",
        href: "/loans/payments",
        icon: CreditCard,
        permissions: [Permissions.LoanRead],
      },
      {
        label: "Operations",
        title: "Batch status & servicing rails",
        href: "/loans/operations",
        icon: Wrench,
        permissions: [
          Permissions.LoanWrite,
          Permissions.LoanWriteOff,
          Permissions.LoanRestructure,
        ],
        permissionMode: "any",
      },
      {
        label: "Reports",
        title: "Portfolio, credit risk, and performance reporting.",
        href: "/loans/reports",
        icon: FileSpreadsheet,
        permissions: [Permissions.LoanRead],
      },
    ],
  },
  {
    id: "configurations",
    label: "Configurations",
    icon: Building2,
    permissions: [
      Permissions.AdminConfigRead,
      Permissions.HolidayRead,
      Permissions.FeeRead,
      Permissions.VelocityLimitRead,
    ],
    items: [
      {
        label: "Overview",
        title: "Bank profile, calendars, fees, and throughput configuration.",
        href: "/configuration",
        icon: Building2,
        permissions: [
          Permissions.AdminConfigRead,
          Permissions.HolidayRead,
          Permissions.FeeRead,
          Permissions.VelocityLimitRead,
        ],
        permissionMode: "any",
      },
      {
        label: "Bank Profile",
        href: "/configuration/bank",
        icon: Building2,
        permissions: [Permissions.AdminConfigRead],
      },
      {
        label: "Holidays",
        href: "/configuration/holidays",
        icon: CalendarDays,
        permissions: [Permissions.HolidayRead],
      },
      {
        label: "Fees",
        href: "/configuration/fees",
        icon: Coins,
        permissions: [Permissions.FeeRead],
      },
      {
        label: "Velocity Limits",
        href: "/configuration/velocity-limits",
        icon: Gauge,
        permissions: [Permissions.VelocityLimitRead],
      },
    ],
  },
  {
    id: "my-account",
    label: "My Account",
    title: "Your profile, credentials, and personal audit trail",
    icon: CircleUser,
    permissions: [
      Permissions.ProfileReadOwn,
      Permissions.PasswordChangeOwn,
      Permissions.MfaManageOwn,
      Permissions.AuditReadOwn,
    ],
    items: [
      {
        label: "Profile",
        href: "/account/profile",
        icon: CircleUser,
        permissions: [Permissions.ProfileReadOwn],
      },
      {
        label: "Change Password",
        href: "/account/password",
        icon: KeyRound,
        permissions: [Permissions.PasswordChangeOwn],
      },
      {
        label: "Multi-Factor Auth",
        href: "/account/mfa",
        icon: ShieldQuestion,
        permissions: [Permissions.MfaManageOwn],
      },
      {
        label: "My Audit Events",
        href: "/account/audit",
        icon: FileSearch,
        permissions: [Permissions.AuditReadOwn],
      },
    ],
  },
];
