import {
  LayoutDashboard,
  Users,
  ShieldCheck,
  Network,
  GitBranch,
  FileSearch,
  FileBarChart2,
  Building2,
  CalendarDays,
  Coins,
  Gauge,
  Landmark,
  Workflow,
  ClipboardCheck,
  CalendarRange,
  FileSpreadsheet,
  KeyRound,
  ShieldQuestion,
  BookOpen,
  Briefcase,
  List,
  HelpCircle,
  TrendingUp,
  FileText,
  Calendar,
  ArrowLeftRight,
  Plus,
  History,
  SearchCheck,
  Wallet,
  PiggyBank,
  CircleUser,
  Contact,
  ListTree,
  Layers,
  Link2,
  Wrench,
  Scale,
  SearchCode,
  AlertTriangle,
  RefreshCw,
  ScrollText,
  ListOrdered,
  UserPlus,
  Search,
  IdCard,
  ClipboardList,
  type LucideIcon,
} from "lucide-react";
import { Permissions } from "@/lib/rbac/permissions";

export interface NavItem {
  /** Shown in the sidebar; keep short when possible. */
  label: string;
  /** Optional longer description for `title` tooltip. */
  title?: string;
  href: string;
  icon?: LucideIcon;
  permissions?: ReadonlyArray<string>;
  permissionMode?: "all" | "any";
}

export interface NavSection {
  id: string;
  /** Shown in the sidebar; keep short (roughly ≤22 chars) so the narrow rail stays clean. */
  label: string;
  /** Optional longer name for tooltips when label is abbreviated. */
  title?: string;
  icon?: LucideIcon;
  items: NavItem[];
  permissions?: ReadonlyArray<string>;
}

export const navSections: NavSection[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    items: [{ label: "Overview", href: "/dashboard", icon: LayoutDashboard }],
  },
  {
    id: "identity",
    label: "Identity & Access",
    title: "User lifecycle, roles, delegations, workflows, audit, compliance",
    icon: Users,
    permissions: [
      Permissions.AdminUsersRead,
      Permissions.AdminRolesRead,
      Permissions.AdminDoaRead,
      Permissions.AuditRead,
      Permissions.ReportGenerate,
    ],
    items: [
      {
        label: "Users",
        title: "User management — /api/v1/identity/users",
        href: "/identity/users",
        icon: Users,
        permissions: [Permissions.AdminUsersRead],
      },
      {
        label: "Roles",
        title: "Role management — /api/v1/identity/roles",
        href: "/identity/roles",
        icon: ShieldCheck,
        permissions: [Permissions.AdminRolesRead],
      },
      {
        label: "Permission catalogue",
        title: "Permission catalogue — GET /api/v1/identity/roles/permissions",
        href: "/identity/permissions",
        icon: ListTree,
        permissions: [Permissions.AdminRolesRead],
      },
      {
        label: "Delegations",
        title: "Delegation of authority — /api/v1/identity/delegations",
        href: "/identity/delegations",
        icon: Network,
        permissions: [Permissions.AdminDoaRead],
      },
      {
        label: "Approval workflows",
        title: "Identity approval workflows — /api/v1/identity/approval-workflows",
        href: "/identity/approval-workflows",
        icon: GitBranch,
        permissions: [Permissions.AdminDoaRead],
      },
      {
        label: "Security audit",
        title: "Cross-user security audit — /api/v1/identity/audit/events",
        href: "/security/audit",
        icon: FileSearch,
        permissions: [Permissions.AuditRead],
      },
      {
        label: "Compliance reports",
        title: "Identity compliance reports — /api/v1/identity/compliance/reports",
        href: "/security/compliance",
        icon: FileBarChart2,
        permissions: [Permissions.ReportGenerate],
      },
    ],
  },
  {
    id: "general-ledger",
    label: "General Ledger",
    icon: BookOpen,
    permissions: [Permissions.GlRead, Permissions.GlApprove],
    items: [
      {
        label: "Overview",
        href: "/general-ledger",
        icon: BookOpen,
        permissions: [Permissions.GlRead, Permissions.GlApprove],
        permissionMode: "any",
      },
      {
        label: "Chart of accounts",
        title: "GL accounts — GET /api/v1/gl/accounts; install standard template via POST /api/v1/gl/setup/chart-of-accounts",
        href: "/general-ledger/chart-of-accounts",
        icon: Layers,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Operational mappings",
        title: "Operational GL types — /api/v1/gl/operational-accounts",
        href: "/general-ledger/operational-accounts",
        icon: Link2,
        permissions: [Permissions.GlRead],
      },
      {
        label: "GL setup",
        title: "Bootstrap chart, mappings, fiscal periods — /api/v1/gl/setup/*",
        href: "/general-ledger/setup",
        icon: Wrench,
        permissions: [Permissions.GlApprove],
      },
      {
        label: "Fiscal periods",
        href: "/general-ledger/fiscal-periods",
        icon: CalendarRange,
        permissions: [Permissions.GlRead],
      },
      {
        label: "GL approvals queue",
        href: "/general-ledger/gl-approvals",
        icon: ClipboardCheck,
        permissions: [Permissions.GlApprove],
      },
      {
        label: "Trial balance",
        title: "Balances — /api/v1/gl/balances/trial-balance",
        href: "/general-ledger/trial-balance",
        icon: Scale,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Transaction lookup",
        title: "GL transactions — GET by id or reference",
        href: "/general-ledger/transaction-lookup",
        icon: SearchCode,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Journal by account",
        title: "Journal lines — GET /api/v1/gl/journal-entries/account/{accountId}",
        href: "/general-ledger/journal-by-account",
        icon: ListOrdered,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Suspense",
        title: "Suspense items — GET /api/v1/gl/suspense",
        href: "/general-ledger/suspense",
        icon: AlertTriangle,
        permissions: [Permissions.GlRead],
      },
      {
        label: "FX revaluation",
        title: "Revaluation runs — /api/v1/gl/revaluation",
        href: "/general-ledger/revaluation",
        icon: RefreshCw,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Audit explorer",
        title: "Audit trail queries — /api/v1/gl/audit/*",
        href: "/general-ledger/audit",
        icon: ScrollText,
        permissions: [Permissions.GlRead],
      },
      {
        label: "Financial statements",
        href: "/general-ledger/reports",
        icon: FileSpreadsheet,
        permissions: [Permissions.GlRead],
      },
    ],
  },
  {
    id: "customers",
    label: "Customers",
    title: "Customer master data & servicing",
    icon: Contact,
    permissions: [Permissions.CustomerRead, Permissions.CustomerWrite],
    items: [
      {
        label: "Overview",
        title: "Customer module routes — /api/v1/customers",
        href: "/customers",
        icon: Contact,
        permissions: [Permissions.CustomerRead, Permissions.CustomerWrite],
        permissionMode: "any",
      },
      {
        label: "Directory",
        title: "Paged customer list — GET /api/v1/customers",
        href: "/customers/directory",
        icon: List,
        permissions: [Permissions.CustomerRead],
      },
      {
        label: "New customer",
        title: "Onboarding — POST /api/v1/customers",
        href: "/customers/new",
        icon: UserPlus,
        permissions: [Permissions.CustomerWrite],
      },
      {
        label: "Lookup",
        title: "By id or tax id — GET /api/v1/customers/{id} or /tax-id/{taxId}",
        href: "/customers/lookup",
        icon: Search,
        permissions: [Permissions.CustomerRead],
      },
      {
        label: "KYC workspace",
        title: "Open KYC tools by customer id — /api/v1/customers/{id}/kyc",
        href: "/customers/kyc-hub",
        icon: ClipboardList,
        permissions: [Permissions.CustomerRead],
      },
      {
        label: "ID documents",
        title: "Open identification documents by customer id — /documents",
        href: "/customers/document-hub",
        icon: IdCard,
        permissions: [Permissions.CustomerPiiRead],
      },
    ],
  },
  {
    id: "accounts",
    label: "Accounts",
    title: "Customer accounts & deposits — /api/v1/accounts",
    icon: Wallet,
    permissions: [Permissions.AccountRead, Permissions.AccountWrite],
    items: [
      {
        label: "Overview",
        href: "/accounts",
        icon: Wallet,
        permissions: [Permissions.AccountRead, Permissions.AccountWrite],
        permissionMode: "any",
      },
      {
        label: "Directory",
        title: "Paged search — GET /api/v1/accounts",
        href: "/accounts/directory",
        icon: List,
        permissions: [Permissions.AccountRead],
      },
      {
        label: "New account",
        title: "Onboarding — POST /api/v1/accounts (customer linkedIdentityUserId)",
        href: "/accounts/new",
        icon: UserPlus,
        permissions: [Permissions.AccountWrite],
      },
      {
        label: "Lookup",
        title: "By id, account number, or IBAN",
        href: "/accounts/lookup",
        icon: Search,
        permissions: [Permissions.AccountRead],
      },
      {
        label: "Portfolio reports",
        title: "Accounts by product type or status — GET /type/{type} & /status/{status}",
        href: "/accounts/reports",
        icon: FileSpreadsheet,
        permissions: [Permissions.AccountRead],
      },
      {
        label: "Operations",
        title: "Batch status/close, dormancy, expired holds, interest accrual",
        href: "/accounts/operations",
        icon: Wrench,
        permissions: [Permissions.AccountWrite],
      },
    ],
  },
  {
    id: "transactions",
    label: "Transactions",
    title: "Transaction management",
    icon: Briefcase,
    permissions: [Permissions.CompensationRead],
    items: [
      {
        label: "Overview",
        href: "/transaction-management",
        icon: Briefcase,
        permissions: [Permissions.CompensationRead],
      },
      {
        label: "Compensation Workflows",
        href: "/operations/compensation",
        icon: Workflow,
        permissions: [Permissions.CompensationRead],
      },
    ],
  },
  {
    id: "exchange-rates",
    label: "Exchange Rates",
    icon: Landmark,
    permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
    items: [
      {
        label: "Currencies",
        href: "/exchange-rates/currencies",
        icon: List,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Currency support",
        href: "/exchange-rates/currency-support",
        icon: HelpCircle,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Latest rate",
        href: "/exchange-rates/latest-rate",
        icon: TrendingUp,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Rate details",
        href: "/exchange-rates/rate-details",
        icon: FileText,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Rate by date",
        href: "/exchange-rates/rate-by-date",
        icon: Calendar,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Convert",
        href: "/exchange-rates/convert",
        icon: ArrowLeftRight,
        permissions: [Permissions.ExchangeRateRead, Permissions.ExchangeRateWrite],
        permissionMode: "any",
      },
      {
        label: "Create rate",
        href: "/exchange-rates/create-rate",
        icon: Plus,
        permissions: [Permissions.ExchangeRateWrite],
      },
      {
        label: "Rate history",
        href: "/exchange-rates/rate-history",
        icon: History,
        permissions: [Permissions.ExchangeRateWrite],
      },
      {
        label: "Rate exists",
        href: "/exchange-rates/rate-exists",
        icon: SearchCheck,
        permissions: [Permissions.ExchangeRateWrite],
      },
    ],
  },
  {
    id: "loans",
    label: "Loans",
    title: "Lending & loan servicing",
    icon: PiggyBank,
    items: [
      {
        label: "Overview",
        href: "/loans",
        icon: PiggyBank,
      },
    ],
  },
  {
    id: "configurations",
    label: "Configurations",
    icon: Building2,
    permissions: [
      Permissions.AdminConfigRead,
      Permissions.HolidayRead,
      Permissions.FeeRead,
      Permissions.VelocityLimitRead,
    ],
    items: [
      {
        label: "Bank Profile",
        href: "/configuration/bank",
        icon: Building2,
        permissions: [Permissions.AdminConfigRead],
      },
      {
        label: "Holidays",
        href: "/configuration/holidays",
        icon: CalendarDays,
        permissions: [Permissions.HolidayRead],
      },
      {
        label: "Fees",
        href: "/configuration/fees",
        icon: Coins,
        permissions: [Permissions.FeeRead],
      },
      {
        label: "Velocity Limits",
        href: "/configuration/velocity-limits",
        icon: Gauge,
        permissions: [Permissions.VelocityLimitRead],
      },
    ],
  },
  {
    id: "my-account",
    label: "My Account",
    title: "Your profile, credentials, and personal audit trail",
    icon: CircleUser,
    permissions: [
      Permissions.ProfileReadOwn,
      Permissions.PasswordChangeOwn,
      Permissions.MfaManageOwn,
      Permissions.AuditReadOwn,
    ],
    items: [
      {
        label: "Profile",
        href: "/account/profile",
        icon: CircleUser,
        permissions: [Permissions.ProfileReadOwn],
      },
      {
        label: "Change Password",
        href: "/account/password",
        icon: KeyRound,
        permissions: [Permissions.PasswordChangeOwn],
      },
      {
        label: "Multi-Factor Auth",
        href: "/account/mfa",
        icon: ShieldQuestion,
        permissions: [Permissions.MfaManageOwn],
      },
      {
        label: "My Audit Events",
        href: "/account/audit",
        icon: FileSearch,
        permissions: [Permissions.AuditReadOwn],
      },
    ],
  },
];
